service: resnet18-inference

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  memorySize: 3008
  timeout: 30
  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "s3:GetObject"
     Resource:
       Fn::Join:
         - ""
         - - "arn:aws:s3:::"
           - "your-bucket-name"
           - "/your-model-name.pt"
plugins:
  - serverless-python-requirements
  - serverless-plugin-warmup

package:
  exclude:
    - venv/**
    - node_modules/**

custom:
  pythonRequirements:
    usePipenv: true
    zip: true

functions:
  inference:
    handler: handler.inference
    warmup: true
    events:
      - http:
         path: inference
         method: post
         cors: true
    layers:
      - arn:aws:lambda:us-east-1:934676248949:layer:pytorchv1-py36:2
